export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED';
export const SORT_INGREDIENTS: 'SORT_INGREDIENTS' = 'SORT_INGREDIENTS';
export const SET_ACTIVE_TAB: 'SET_ACTIVE_TAB' = 'SET_ACTIVE_TAB';
export const INCREASE_ADDED_INGREDIENT: 'INCREASE_ADDED_INGREDIENT' = 'INCREASE_ADDED_INGREDIENT';
export const DECREASE_ADDED_INGREDIENT: 'DECREASE_ADDED_INGREDIENT' = 'DECREASE_ADDED_INGREDIENT';
export const CLEAR_ADDED_INGREDIENT: 'CLEAR_ADDED_INGREDIENT' = 'CLEAR_ADDED_INGREDIENT';
