export const WS_ORDERS_ALL_CONNECTION_INIT: 'WS_ORDERS_ALL_CONNECTION_INIT' = 'WS_ORDERS_ALL_CONNECTION_INIT';
export const WS_ORDERS_ALL_CONNECTION_SUCCESS: 'WS_ORDERS_ALL_CONNECTION_SUCCESS' = 'WS_ORDERS_ALL_CONNECTION_SUCCESS';
export const WS_ORDERS_ALL_CONNECTION_ERROR: 'WS_ORDERS_ALL_CONNECTION_ERROR' = 'WS_ORDERS_ALL_CONNECTION_ERROR';
export const WS_ORDERS_ALL_CONNECTION_CLOSED: 'WS_ORDERS_ALL_CONNECTION_CLOSED' = 'WS_ORDERS_ALL_CONNECTION_CLOSED';
export const WS_ORDERS_ALL_GET_MESSAGE: 'WS_ORDERS_ALL_GET_MESSAGE' = 'WS_ORDERS_ALL_GET_MESSAGE';
export const WS_ORDERS_ALL_SEND_MESSAGE: 'WS_ORDERS_ALL_SEND_MESSAGE' = 'WS_ORDERS_ALL_SEND_MESSAGE';
export const WS_ORDERS_ALL_CLOSE_CONNECTION: 'WS_ORDERS_ALL_CLOSE_CONNECTION' = 'WS_ORDERS_ALL_CLOSE_CONNECTION';

export const WS_ORDERS_USER_CONNECTION_INIT: 'WS_ORDERS_USER_CONNECTION_INIT' = 'WS_ORDERS_USER_CONNECTION_INIT';
export const WS_ORDERS_USER_CONNECTION_SUCCESS: 'WS_ORDERS_USER_CONNECTION_SUCCESS' = 'WS_ORDERS_USER_CONNECTION_SUCCESS';
export const WS_ORDERS_USER_CONNECTION_ERROR: 'WS_ORDERS_USER_CONNECTION_ERROR' = 'WS_ORDERS_USER_CONNECTION_ERROR';
export const WS_ORDERS_USER_CONNECTION_CLOSED: 'WS_ORDERS_USER_CONNECTION_CLOSED' = 'WS_ORDERS_USER_CONNECTION_CLOSED';
export const WS_ORDERS_USER_GET_MESSAGE: 'WS_ORDERS_USER_GET_MESSAGE' = 'WS_ORDERS_USER_GET_MESSAGE';
export const WS_ORDERS_USER_SEND_MESSAGE: 'WS_ORDERS_USER_SEND_MESSAGE' = 'WS_ORDERS_USER_SEND_MESSAGE';
export const WS_ORDERS_USER_CLOSE_CONNECTION: 'WS_ORDERS_USER_CLOSE_CONNECTION' = 'WS_ORDERS_USER_CLOSE_CONNECTION';
