export const FORGOT_REQUEST: 'FORGOT_REQUEST' = 'FORGOT_REQUEST';
export const FORGOT_SUCCESS: 'FORGOT_SUCCESS' = 'FORGOT_SUCCESS';
export const FORGOT_INITIAL: 'FORGOT_INITIAL' = 'FORGOT_INITIAL';
export const FORGOT_FAILED: 'FORGOT_FAILED' = 'FORGOT_FAILED';

export const RESET_REQUEST: 'RESET_REQUEST' = 'RESET_REQUEST';
export const RESET_SUCCESS: 'RESET_SUCCESS' = 'RESET_SUCCESS';
export const RESET_INITIAL: 'RESET_INITIAL' = 'RESET_INITIAL';
export const RESET_FAILED: 'RESET_FAILED' = 'RESET_FAILED';

export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const USER_DATA_REQUEST: 'USER_DATA_REQUEST' = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS: 'USER_DATA_SUCCESS' = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILED: 'USER_DATA_FAILED' = 'USER_DATA_FAILED';

export const CHANGE_USER_DATA_REQUEST: 'CHANGE_USER_DATA_REQUEST' = 'CHANGE_USER_DATA_REQUEST';
export const CHANGE_USER_DATA_SUCCESS: 'CHANGE_USER_DATA_SUCCESS' = 'CHANGE_USER_DATA_SUCCESS';
export const CHANGE_USER_DATA_FAILED: 'CHANGE_USER_DATA_FAILED' = 'CHANGE_USER_DATA_FAILED';

export const SET_USER: 'SET_USER' = 'SET_USER';
export const CLEAR_USER: 'CLEAR_USER' = 'CLEAR_USER';
